version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - /opt/elk/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - /opt/elk/cert:/usr/share/cert
      - /opt/elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - /opt/elk/cert:/usr/share/cert
    ports:
      - "5601:5601"
    links:
      - elasticsearch
